// export const GET_LOCATIONS = 'GET_LOCATIONS';
// export const GET_WEATHER = 'GET_WEATHER_FOR_LOCATIONS';
// export const GET_LONG_TERM_WEATHER = 'GET_WEATHER_FOR_LOCATIONS';
// export const GET_USER_LOCATION = 'GET_USER_LOCATION';

export const UPDATE_SEARCH_LOCATION = 'UPDATE_SEARCH_LOCATION';
export const UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';

